variables:
  GIT_SSL_NO_VERIFY: "true"
before_script:
test:
    image: python:3-alpine
    script:
        - pip install -r requirements/test.txt
        - python -m unittest discover
        - py.test --cov=aws

